image: alpine/edge
packages:
  - go
secrets:
  - f81fca6d-0276-4087-af74-711044e181fa
tasks:
  - setup: |
      cd gozer
      go get .
  - build: |
      cd gozer
      go build -v ./...
  - test: |
      cd gozer
      go test
  - github_mirror: |
      cd gozer
      git config --global credential.helper store
      git push https://github.com/dannyvankooten/gozer.git --mirror
